/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as BoutiqueRouteImport } from './routes/boutique'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as ManifestDotwebmanifestRouteImport } from './routes/manifest[.]webmanifest'
import { Route as ProductIdRouteImport } from './routes/product.$id'
import { Route as ApiPublicMigrateHelperRouteImport } from './routes/api/public/migrate-helper'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const BoutiqueRoute = BoutiqueRouteImport.update({
  id: '/boutique',
  path: '/boutique',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const ManifestDotwebmanifestRoute = ManifestDotwebmanifestRouteImport.update({
  id: '/manifest.webmanifest',
  path: '/manifest.webmanifest',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductIdRoute = ProductIdRouteImport.update({
  id: '/product/$id',
  path: '/product/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicMigrateHelperRoute = ApiPublicMigrateHelperRouteImport.update({
  id: '/api/public/migrate-helper',
  path: '/api/public/migrate-helper',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/boutique': typeof BoutiqueRoute
  '/checkout': typeof CheckoutRoute
  '/manifest.webmanifest': typeof ManifestDotwebmanifestRoute
  '/product/$id': typeof ProductIdRoute
  '/api/public/migrate-helper': typeof ApiPublicMigrateHelperRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/boutique': typeof BoutiqueRoute
  '/checkout': typeof CheckoutRoute
  '/manifest.webmanifest': typeof ManifestDotwebmanifestRoute
  '/product/$id': typeof ProductIdRoute
  '/api/public/migrate-helper': typeof ApiPublicMigrateHelperRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/boutique': typeof BoutiqueRoute
  '/checkout': typeof CheckoutRoute
  '/manifest.webmanifest': typeof ManifestDotwebmanifestRoute
  '/product/$id': typeof ProductIdRoute
  '/api/public/migrate-helper': typeof ApiPublicMigrateHelperRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/boutique'
    | '/checkout'
    | '/manifest.webmanifest'
    | '/product/$id'
    | '/api/public/migrate-helper'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/boutique'
    | '/checkout'
    | '/manifest.webmanifest'
    | '/product/$id'
    | '/api/public/migrate-helper'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/boutique'
    | '/checkout'
    | '/manifest.webmanifest'
    | '/product/$id'
    | '/api/public/migrate-helper'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  BoutiqueRoute: typeof BoutiqueRoute
  CheckoutRoute: typeof CheckoutRoute
  ManifestDotwebmanifestRoute: typeof ManifestDotwebmanifestRoute
  ProductIdRoute: typeof ProductIdRoute
  ApiPublicMigrateHelperRoute: typeof ApiPublicMigrateHelperRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/boutique': {
      id: '/boutique'
      path: '/boutique'
      fullPath: '/boutique'
      preLoaderRoute: typeof BoutiqueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manifest.webmanifest': {
      id: '/manifest.webmanifest'
      path: '/manifest.webmanifest'
      fullPath: '/manifest.webmanifest'
      preLoaderRoute: typeof ManifestDotwebmanifestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/product/$id': {
      id: '/product/$id'
      path: '/product/$id'
      fullPath: '/product/$id'
      preLoaderRoute: typeof ProductIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/migrate-helper': {
      id: '/api/public/migrate-helper'
      path: '/api/public/migrate-helper'
      fullPath: '/api/public/migrate-helper'
      preLoaderRoute: typeof ApiPublicMigrateHelperRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  BoutiqueRoute: BoutiqueRoute,
  CheckoutRoute: CheckoutRoute,
  ManifestDotwebmanifestRoute: ManifestDotwebmanifestRoute,
  ProductIdRoute: ProductIdRoute,
  ApiPublicMigrateHelperRoute: ApiPublicMigrateHelperRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
